name: ContemporaryArt
favicon: null
layout_spectrum: 0.2221035
typography_spectrum: 0.7902658
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Contemporary Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27271f'
    - '#454138'
    - '#7a7059'
    - '#d6d0b0'
    - '#aba78e'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.4627167
purpose: []
