layout_spectrum: 0.2221035
typography_spectrum: 0.7902658
color:
  lightness: 0.5382636
  brandStrength: 0.5869235
  saturation: 0.8038459
  rhythmicContrast: 0.4627167
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: ContemporaryartNationalgallery
